MIN_CHAR_USERNAME = 3
MAX_CHAR_USERNAME = 12
MIN_CHAR_PASSWORD = 4
MAX_CHAR_PASSWORD = 20
# MIN_CHAR_EMAIL = 8
# MAX_CHAR_EMAIL = 320
MIN_CHAR_NAME = 5
MAX_CHAR_NAME = 100
NAME_PATTERN = rf"^(?=.{{{MIN_CHAR_NAME},{MAX_CHAR_NAME}}}$)[A-Za-zÀ-ÿ]+(?:\s+[A-Za-zÀ-ÿ]+)+$"
USERNAME_PATTERN = rf"^[a-zA-Z0-9_.]{{{MIN_CHAR_USERNAME},{MAX_CHAR_USERNAME}}}$"
PASSWORD_PATTERN = rf"^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)[A-Za-z\d@$!%*?&]{{{MIN_CHAR_PASSWORD},{MAX_CHAR_PASSWORD}}}$"
# EMAIL_PATTERN = r"^[a-zA-Z0-9_.+-]{1,64}@[a-zA-Z0-9-]{1,255}\.[a-zA-Z]{2,10}$"
